Mobilek/Mobilek.MVC/Controllers/UserAccountController.cs
using Mobilek.DTO;
using Mobilek.MVC.Models;
using Mobilek.Services;
using Mobilek;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Mvc;
using Mobilek.MVC.Controllers;
using Mobilek.MVC.ViewModels;
using Mobilek.MVC.Constants;
using AutoMapper;
using Mobilek.MVC.Helpers;
using System.Text;
using System.Dynamic;
namespace MobilekMVC.Controllers
{
    [Authorize]
    public class UserAccountController : Controller
    {
        private readonly ICustomerDTOService _customerService;
        private readonly IOrderDTOService _orderService;
        private readonly IStationDTOService _stationService;
        private readonly ICarDTOService _carService;
        public UserAccountController(ICarDTOService carDtoService, IStationDTOService stationDtoService, IOrderDTOService orderDtoService, ICustomerDTOService customerDtoService)
        {
            _customerService = customerDtoService;
            _orderService = orderDtoService;
            _stationService = stationDtoService;
            _carService = carDtoService;
        }

        #region Profile

        [HttpGet]
        [Authorize(Roles = Roles.UserRole)]
        public ActionResult UserProfile()
        {
            var cust = Task.Run(() => _customerService.Get(User.Identity.Name)).Result;
            EditProfileViewModel regi = Mapper.Map<EditProfileViewModel>(cust);
            return View(regi);
        }

        [Authorize(Roles = Roles.UserRole)]
        [HttpPost]
        public ActionResult UserProfile(EditProfileViewModel model, string returnUrl)
        {
            string msg;
            CustomerDTO cust = new CustomerDTO();
            try
            {
                if (ModelState.IsValid)
                {
                    cust = Task.Run(() => _customerService.Get(User.Identity.Name)).Result;
                    model.password = cust.password;
                    CustomerDTO customer = Mapper.Map<CustomerDTO>(model);
                    customer.Id = cust.Id;
                    
                    var custPut = Task.Run((() => _customerService.Put(customer))).Result;
                    if (custPut)
                        msg = "Saved Successfully";
                    else
                    {
                        msg = "Something went wrong";
                        ModelState.AddModelError("", msg);
                        RedirectToRoute(returnUrl);
                    }
                }
                else
                {
                    msg = "Validation profie not successfull";
                    ModelState.AddModelError("", msg);
                    RedirectToRoute(returnUrl);
                }
            }
            catch (Exception ex)
            {
                msg = "Error occured:" + ex.Message;
                ModelState.AddModelError("", msg);
                RedirectToRoute(returnUrl);
            }

            model.IsEdited = true;

            //model = Mapper.Map<EditProfileViewModel>(cust);
            return View(model);
        }
        #endregion

        #region Order History
        [HttpGet]
        [Authorize(Roles = Roles.UserRole)]
        public ActionResult OrderHistory()
        {
            List<OrderModel> allOrders = new List<OrderModel>();
            var orders = GetOrders();
            foreach (OrderDTO o in orders)
            {
                var carList = GetCars(o.Id);
                allOrders.Add(new OrderModel { order = o, cars = carList });
            }
            return View(allOrders);
        }

        public List<OrderDTO> GetOrders()
        {
            var orders = Task.Run(() => _orderService.Get()).Result;
            var orderList = orders.Where(o => o.Customer.userName.Equals(User.Identity.Name));
            return orderList.ToList();
        }
        private List<CarDTO> GetCars(int id)
        {
            var order = Task.Run(() => _orderService.Get(id)).Result;
            return order.Cars.ToList();
        }
        #endregion

        #region Make Order

        [HttpGet]
        [Authorize(Roles = Roles.UserRole)]
        public ActionResult MakeOrder()
        {
            List<SelectListItem> cars = Task.Run(() => _carService.Get()).Result
                .Select(s => new SelectListItem()
                {
                    Value = s.Id.ToString(),
                    Text = s.brand + " " + s.model

                }).ToList();
            ViewBag.cars = cars;

            var stations = GetStations();
            IEnumerable<SelectListItem> items = Task.Run(() => _stationService.Get()).Result.Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.street + " " + c.streetNumer
            }).ToList();
            ViewBag.Stationss = items;
            return View();
        }

        [HttpPost]
        [Authorize(Roles = Roles.UserRole)]
        public ActionResult MakeOrder(MakeOrderModel model)
        {
            string msg = "";
            if (ModelState.IsValid)
            {
                try{
                    var cust = Task.Run(() => _customerService.Get(User.Identity.Name)).Result;
                    StationDTO station = Task.Run(() => _stationService.Get(model.stationItem)).Result;
                    List<CarDTO> cars = new List<CarDTO>();
                    foreach (int i in model.carItems)
                    {
                        cars.Add(Task.Run(() => _carService.Get(i)).Result);
                    }
                    OrderDTO order = new OrderDTO()
                    {
                        customerId = cust.Id,
                        endDate = model.endingDate,
                        startDate = model.startingDate,
                        returnStationId = station.Id,
                        isFinished = (model.endingDate<DateTime.Now),
                        workerId = 1,
                        Cars = cars
                    };
                    var result = Task.Run(() => _orderService.Post(order)).Result;
                }catch(Exception e){
                    msg = "Error occured:" + e.Message;
                }
            }
            else
            {
                msg = "Oder submission not successfull";
            }
            if (msg == "")
            {

            }
            else
            {
                ModelState.AddModelError("", msg);
            }

            List<SelectListItem> carList = Task.Run(() => _carService.Get()).Result
                .Select(s => new SelectListItem()
                {
                    Value = s.Id.ToString(),
                    Text = s.brand + " " + s.model

                }).ToList();
            ViewBag.cars = carList;

            IEnumerable<SelectListItem> items = Task.Run(() => _stationService.Get()).Result.Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.street + " " + c.streetNumer
            });
            ViewBag.Stationss = items.ToList();
            return View();
        }

       public List<StationDTO> GetStations()
        {
            var stations = Task.Run(() => _stationService.Get()).Result;
            return stations.ToList();
        }
       
        [HttpPost]
        [Authorize(Roles = Roles.UserRole)]
        public string GetModels(string brand)
        {
            var models = FrenchApi.GetCarsByBrand(brand).Select(s => s.modele_dossier).ToList();

            StringBuilder result = new StringBuilder();
            foreach (var s in models)
            {
                result.Append("<option value=" + '\"' + s + '\"' + " > " + s + " </option> ");
            }
            return result.ToString();

        }
        #endregion
    }
}

Mobilek/Mobilek.MVC/Controllers/WorkerController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using Mobilek.DTO;
using Mobilek.MVC.Constants;
using Mobilek.MVC.Helpers;
using Mobilek.Services;

namespace Mobilek.MVC.Controllers
{

    public class WorkerController : Controller
    {

        private readonly ICarDTOService _carDtoService;
        private readonly IStationDTOService _stationjDtoService;
        public WorkerController(ICarDTOService carDtoService,IStationDTOService stationDtoService)
        {
            _carDtoService = carDtoService;
            _stationjDtoService = stationDtoService;
        }

        [Authorize(Roles = Roles.AdminRole)]
        // GET: Worker
        public ActionResult Index()
        {
            return View();
        }

        #region car
        [HttpGet]
        public JsonResult GetCars(string sidx, string sord, int page, int rows)  //Gets the todo Lists.
        {
            int pageIndex = Convert.ToInt32(page) - 1;
            int pageSize = rows;

            var records = Task.Run(() => _carDtoService.Get()).Result.AsQueryable();

            int totalRecords = records.Count();
            var totalPages = (int)Math.Ceiling((float)totalRecords / (float)rows);
            if (sord.ToUpper() == "DESC")
            {
                records = records.OrderByDescending(s => s.brand);
                records = records.Skip(pageIndex * pageSize).Take(pageSize);
            }
            else
            {
                records = records.OrderBy(s => s.brand);
                records = records.Skip(pageIndex * pageSize).Take(pageSize);
            }
            var jsonData = new
            {
                total = totalPages,
                page,
                records = totalRecords,
                rows = records
            };
            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public JsonResult GetStationCars()
        {
            var stations = Task.Run((() => _stationjDtoService.Get())).Result.Select(s=>s.city + " "+s.street);
            return Json(stations, JsonRequestBehavior.AllowGet);
        }
        [Authorize(Roles = Roles.AdminRole)]
        [HttpPost]
        public string CreateCar([Bind(Exclude = "Id")] CarDTO objTodo)
        {
            string msg;
            try
            {
                if (ModelState.IsValid)
                {
                    
                    var mod= FrenchApi.GetCarByBrandAndModel(objTodo.brand,objTodo.model);
                    var stations = Task.Run(() => _stationjDtoService.Get()).Result;
                    var station = stations.FirstOrDefault(s => objTodo.stationName.Contains(s.street));

                    if (mod != null && station!=null)
                    {
                        objTodo.frenchId = mod.recordid;
                        objTodo.stationId = station.Id;
                        var carpost = Task.Run((() => _carDtoService.Post(objTodo))).Result;
                        msg = Messages.SuccessAdd;
                    }
                    else
                    {
                        msg = Messages.ValidationFail;
                    }
                    
                }
                else
                {
                    msg = Messages.ValidationFail;
                }
            }
            catch (Exception ex)
            {
                msg = Messages.ErrorOccured + ex.Message;
            }
            return msg;
        }
        [HttpGet]
        public JsonResult GetFrenchCars()
        {
            var brandNames = FrenchApi.GetUniqueBrandCars(); 
            return Json(brandNames, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public string GetModels(string brand)
        {
            var models = FrenchApi.GetCarsByBrand(brand).Select(s => s.modele_dossier).ToList();

            StringBuilder result = new StringBuilder();
            foreach (var s in models)
            {
                result.Append("<option value=" + '\"' + s + '\"' + " > " + s + " </option> ");
            }
            return result.ToString();

        }
        [Authorize(Roles = Roles.AdminRole)]
        [HttpPost]
        public string EditCar(CarDTO objTodo)
        {
            string msg;
            try
            {
                if (ModelState.IsValid)
                {

                    var mod = FrenchApi.GetCarByBrandAndModel(objTodo.brand, objTodo.model);

                    var stations = Task.Run((() => _stationjDtoService.Get())).Result;
                    var station = stations.FirstOrDefault(s => objTodo.stationName.Contains(s.city));
                    if (station!=null && mod!=null)
                    {
                        objTodo.stationId = station.Id;
                        objTodo.frenchId = mod.recordid;
                    }

                    var carput = Task.Run((() => _carDtoService.Put(objTodo))).Result;
                    if(carput)
                        msg = Messages.SuccessAdd;
                    else
                    {
                        msg = Messages.UnexcpectedError;
                    }
                }
                else
                {
                    msg = Messages.ValidationFail;
                }
            }
            catch (Exception ex)
            {
                msg = Messages.ErrorOccured + ex.Message;
            }
            return msg;
        }


        #endregion


        #region Station
        [Authorize(Roles = Roles.AdminRole)]
        [HttpGet]
        public JsonResult GetStations(string sidx, string sord, int page, int rows)
        {
            int pageIndex = Convert.ToInt32(page) - 1;
            int pageSize = rows;

            var records = Task.Run(() => _stationjDtoService.Get()).Result.AsQueryable();

            int totalRecords = records.Count();
            var totalPages = (int)Math.Ceiling((float)totalRecords / (float)rows);
            if (sord.ToUpper() == "DESC")
            {
                records = records.OrderByDescending(s => s.city);
                records = records.Skip(pageIndex * pageSize).Take(pageSize);
            }
            else
            {
                records = records.OrderBy(s => s.city);
                records = records.Skip(pageIndex * pageSize).Take(pageSize);
            }
            var jsonData = new
            {
                total = totalPages,
                page,
                records = totalRecords,
                rows = records
            };
            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }



        [HttpPost]
        [Authorize(Roles = Roles.AdminRole)]
        public string CreateStation([Bind(Exclude = "Id")] StationDTO objTodo)
        {
            string msg;
            try
            {
                if (ModelState.IsValid)
                {
                    var carpost = Task.Run((() => _stationjDtoService.Post(objTodo))).Result;
                    msg = Messages.SuccessAdd;
                }
                else
                {
                    msg = Messages.ValidationFail;
                }
            }
            catch (Exception ex)
            {
                msg = Messages.ErrorOccured + ex.Message;
            }
            return msg;
        }
        [Authorize(Roles = Roles.AdminRole)]
        public string EditStation(StationDTO objTodo)
        {
            string msg;
            try
            {
                if (ModelState.IsValid)
                {
                    var carpost = Task.Run((() => _stationjDtoService.Put(objTodo))).Result;
                    msg = Messages.SuccessAdd;
                }
                else
                {
                    msg = Messages.ValidationFail;
                }
            }
            catch (Exception ex)
            {
                msg = Messages.ErrorOccured + ex.Message;
            }
            return msg;
        }
        [Authorize(Roles = Roles.AdminRole)]
        public string DeleteStation(int Id)
        {
            var station =Task.Run(() => _stationjDtoService.Get(Id)).Result;
            if (station != null)
            {
                var result = Task.Run(() => _stationjDtoService.Delete(Id)).Result;
                if (result)
                {
                    return Messages.SuccessDelete;
                }
            }
            return Messages.StationDeleteFail;
        }
        #endregion
    }
}

Mobilek/Mobilek.MVC/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using Microsoft.AspNet.Identity
@using Mobilek.MVC.Constants;
@using Roles = Mobilek.MVC.Constants.Roles
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Modern Business - @ViewBag.Title</title>

    <!-- Bootstrap -->
    <link href="@Url.Content("/css/bootstrap.css")" rel="stylesheet">
    <link href="@Url.Content("/css/modern-business.css")" rel="stylesheet">
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    @RenderSection("scripts", required: false)


    <link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
    <link href="~/Content/jquery.jqGrid/ui.jqgrid.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-2.2.0.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery-2.2.0.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.10.0.min.js"></script>
    <script src="~/Scripts/i18n/grid.locale-en.js"></script>
    <script src="~/Scripts/jquery.jqGrid.min.js"></script>
    <script src="~/Scripts/CarGrid.js"></script>
    <script src="~/Scripts/StationGrid.js"></script>
    <link href="~/css/ColorCombo.css" rel="stylesheet" />



</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!-- You'll want to use a responsive image option so this logo looks good on devices - I recommend using something like retina.js (do a quick Google search for it and you'll find it) -->
            @Html.ActionLink("Mobilek", "Index", new {controller = "Home"}, new {@class = "navbar-brand"})
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav navbar-right">
                @*<li id="about">
                    @Html.ActionLink("About", "Index", "About")
                </li>*@
                <li id="account">

                    @if (Request.IsAuthenticated)
                    {

                        <li>
                            @Ajax.ActionLink("LogOff", "LogOff", "Account", routeValues: null, ajaxOptions: new AjaxOptions {HttpMethod = "POST"})

                        </li>
                        <li>
                            @Html.ActionLink(((ClaimsIdentity) User.Identity).Claims.Single(s => s.Type == ClaimTypes.Role).Value + " " + User.Identity.GetUserName() + "!", "Index", "Manage", routeValues: null, htmlAttributes: new {title = "Manage"})
                        </li>
                    }
                    else
                    {

                        <li>@Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new {id = "registerLink"})</li>
                        <li>@Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new {id = "loginLink"})</li>

                    }
                </li>
                @if (Request.IsAuthenticated)
                {
                    string role = "";
                    var claim = ((ClaimsIdentity)User.Identity).Claims.FirstOrDefault(s => s.Type == ClaimTypes.Role);
                    if (claim != null)
                    {
                        role = claim.Value;
                    }
                    if (role == Roles.AdminRole)
                    {
                        <li id="worker">
                            @Html.ActionLink("Worker Panel", "Index", "Worker")
                        </li>
                    }

                    else if (role == Roles.UserRole)
                    {
                        <li id="user">
                            @Html.ActionLink("User Panel", "UserProfile", "UserAccount")
                        </li>
                    }

                }
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

@RenderBody()

<div class="container">
    <hr>
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Anna Kosiorek & Mateusz Kwieciński 2016</p>
            </div>
        </div>
    </footer>

</div>
</body>
</html>